### ISSUE TITLE
Unable to go past Create New Model using default dataset example

### ISSUE THREAD

**Issue by sujitpal** [megagonlabs/ruler#3]
I am trying to run RULER using the spam_example dataset. I am able to start the server and client and navigate to localhost:3000 without problems.

In step 1, I choose "spam_dataset" and go to step 2, where I select "create new model" and name it something like spam_example. The Continue button remains gray and I see the following error on the server.

```
127.0.0.1 - - [08/Dec/2020 21:15:08] "POST /api/models/spam_example HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 173, in wrapper
    response = function(request)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/connexion/decorators/validation.py", line 388, in wrapper
    return function(request)
  File "/home/ubuntu/anaconda3/envs/ruler/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/home/ubuntu/labs-sentence-assertion-detector/ruler/server/api/endpoints.py", line 132, in create_new_model
    project.modeler = Modeler(cardinality=project.cardinality, name=model_name)
TypeError: __init__() got an unexpected keyword argument 'name'
```
On the client side (`npm start`), the console shows the following, although this is on startup, not as response to the particular request.

```
Compiled with warnings.

./src/SelectedSpan.js
  Line 12:  'DIR_LINK' is defined but never used  no-unused-vars

./src/ProjectCreation/DatasetSelect.js
  Line 167:  'fi' is defined but never used  no-unused-vars

./src/AnnotationDisplay.js
  Line 198:  'offset' is defined but never used  no-unused-vars

./src/reducers/saveFileReducer.js
  Line 1:  'SAVE_SUCCESS' is defined but never used  no-unused-vars
  Line 1:  'SAVE_PENDING' is defined but never used  no-unused-vars
  Line 12:  Unreachable code                          no-unreachable

./src/ProjectCreation/ProjectCreation.js
  Line 21:    'launch' is defined but never used   no-unused-vars
  Line 152:  Expected '===' and instead saw '=='  eqeqeq

./src/actions/annotate.js
  Line 70:  'match' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
```

I am using a conda environment with Python 3.6 on the server side, and node.js version 9.10.1 and npm version 5.6.0.

I am hoping to use RULER to compare against writing Snorkel Labeling functions by hand for a data programming effort, so once I am past this hurdle I hope to use my own dataset and label it.

Thank you for creating this, and any help in resolving the issue above would be greatly appreciated.

**Comment by rschmaelzle** [comment]
hello, I have the same issue. any help would be appreciated.
